# Code Generated by Sidekick is for learning and experimentation purposes only.

import streamlit as st
import pandas as pd
import configparser
import firebase_admin
from firebase_admin import credentials, firestore
from PIL import Image
import random

# --- FIRESTORE SETUP ---
def get_firestore_client():
    try:
        creds_dict = dict(st.secrets["firestore_service_account"])
        creds_dict["private_key"] = creds_dict["private_key"].replace('\\n', '\n')
    except Exception:
        config = configparser.ConfigParser(interpolation=None)
        config.read('secrets.ini')
        fs_creds = config['firestore_service_account']
        creds_dict = {
            "type": fs_creds["type"],
            "project_id": fs_creds["project_id"],
            "private_key_id": fs_creds["private_key_id"],
            "private_key": fs_creds["private_key"].replace('\\n', '\n'),
            "client_email": fs_creds["client_email"],
            "client_id": fs_creds["client_id"],
            "auth_uri": fs_creds["auth_uri"],
            "token_uri": fs_creds["token_uri"],
            "auth_provider_x509_cert_url": fs_creds["auth_provider_x509_cert_url"],
            "client_x509_cert_url": fs_creds["client_x509_cert_url"],
            "universe_domain": fs_creds.get("universe_domain", "googleapis.com")
        }
    if not firebase_admin._apps:
        cred = credentials.Certificate(creds_dict)
        firebase_admin.initialize_app(cred)
    return firestore.client()

db = get_firestore_client()

# --- CONFIGURATION ---
HOST_SECRET = "123"
EXCEL_FILE = "employee_info1.xlsx"

# --- SESSION STATE INITIALIZATION ---
if "registered" not in st.session_state:
    st.session_state.registered = False
if "user_name" not in st.session_state:
    st.session_state.user_name = None
if "game_started" not in st.session_state:
    st.session_state.game_started = False
if "host_mode" not in st.session_state:
    st.session_state.host_mode = False

st.title("FunFriday Meme Game")

# --- LOAD EMPLOYEE DATA ---
@st.cache_data
def load_employee_data():
    df = pd.read_excel(EXCEL_FILE)
    for col in ["Name", "Image URL"]:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")
    return df

try:
    df = load_employee_data()
except Exception as e:
    st.error(f"Error loading employee data: {e}")
    st.stop()

employee_names_original = df["Name"].tolist()

# --- FIRESTORE HELPERS ---
def get_game_state():
    doc = db.collection("game_state").document("current").get()
    return doc.to_dict() if doc.exists else None

def set_game_state(state):
    db.collection("game_state").document("current").set(state)

def get_leaderboard():
    docs = db.collection("leaderboard").stream()
    return {doc.id: doc.to_dict().get("score", 0) for doc in docs}

def set_leaderboard_entry(name, score=0):
    db.collection("leaderboard").document(name).set({"Name": name, "score": score})

def reset_firestore_state():
    db.collection("game_state").document("current").set({
        "current_index": 0,
        "current_meme": None,
        "game_started": False,
        "game_over": False
    })

def reset_leaderboard():
    leaderboard_ref = db.collection("leaderboard")
    for doc in leaderboard_ref.stream():
        doc.reference.delete()

def reset_guesses():
    guesses_ref = db.collection("game_state").document("current").collection("guesses")
    for doc in guesses_ref.stream():
        doc.reference.delete()

# leaderboard = get_leaderboard()
# if (st.session_state.get("registered", False)
#     and st.session_state.get("user_name") not in leaderboard
# ):
#     st.session_state.registered = False
#     st.session_state.user_name = None

# --- REGISTRATION (REQUIRED) ---
if not st.session_state.registered:
    st.subheader("Register to Play")
    reg_name = st.text_input("Enter your name (this will appear on the leaderboard):", key="reg_input")
    if st.button("Register"):
        if reg_name and reg_name.strip():
            st.session_state.user_name = reg_name.strip()
            st.session_state.registered = True
            # Add to leaderboard if not already present
            leaderboard = get_leaderboard()
            if reg_name.strip() not in leaderboard:
                set_leaderboard_entry(reg_name.strip(), 0)
            st.success(f"Welcome, {reg_name.strip()}! You are now registered and can play.")
            st.rerun()
        else:
            st.warning("Please enter a name to register.")
    st.stop()
else:
    if st.session_state.host_mode:
        st.info(f"Welcome, {st.session_state.user_name}!. You are the host. Use the controls in the sidebar to start or manage the game.")
    else:
        st.info(f"Welcome, {st.session_state.user_name}! Wait for the host to start the game." if not get_game_state() or not get_game_state().get("game_started", False) else "")

# --- HOST CONTROLS ---
with st.sidebar:
    st.header("Host Controls")
    if not st.session_state.host_mode:
        host_code = st.text_input("Enter host secret to unlock controls", type="password")
        if st.button("Unlock Host Controls"):
            if host_code == HOST_SECRET:
                st.session_state.host_mode = True
                st.success("Host controls unlocked!")
                st.rerun()
            else:
                st.error("Incorrect secret.")
    else:
        game_state = get_game_state()
        if not game_state or not game_state.get("game_started", False):
            if st.button("Start Game"):
                reset_firestore_state()
                reset_guesses()
                set_game_state({
                    "current_index": 0,
                    "current_meme": None,
                    "game_started": True,
                    "game_over": False
                })
                reset_leaderboard()
                st.rerun()
        else:
            if st.button("Stop Game"):
                set_game_state({**game_state, "game_started": False})
                st.rerun()
        if st.button("Reset Game"):
            reset_firestore_state()
            reset_leaderboard()
            reset_guesses()
            st.session_state.host_mode = False
            st.rerun()

    # Leaderboard (Visible to everyone in the sidebar)
    st.subheader("Leaderboard (Top 5)")
    leaderboard = get_leaderboard()
    sorted_leaderboard = sorted(leaderboard.items(), key=lambda x: x[1], reverse=True)[:5]
    for i, (uname, score) in enumerate(sorted_leaderboard, 1):
        st.write(f"{i}. {uname}: {score}")

# --- GAME PHASE ---
game_state = get_game_state()

if not st.session_state.host_mode:
    if st.button("Refresh"):
        st.rerun()

if game_state and game_state.get("game_over", False):
    st.success("Game Over! All employees have had their meme.")
    st.balloons()
    st.stop()

if game_state and game_state.get("game_started", False):
    idx = game_state["current_index"]
    if idx >= len(df):
        if not game_state.get("game_over", False):
            set_game_state({**game_state, "game_started": False, "game_over": True})
        st.success("🎉 Game over! Thanks for playing!")
        st.balloons()
        st.stop()

    emp = df.iloc[idx]
    image_url = emp["Image URL"]
    correct_name_original = emp["Name"]
    correct_name_lower = correct_name_original.lower()
    img = Image.open(image_url)
    desired_width = 400
    aspect_ratio = img.height / img.width
    new_height = int(desired_width * aspect_ratio)
    resized_img = img.resize((desired_width, new_height))

    # Store the image URL in Firestore for the current round
    if not game_state.get("current_meme"):
        set_game_state({**game_state, "current_meme": image_url})
        game_state = get_game_state()  # Refresh

    st.header("Guess Who?")
    st.image(resized_img, use_container_width=False)

    # --- Dropdown with 8 random names including correct one, stable per round ---
    if "dropdown_names" not in st.session_state or st.session_state.get("dropdown_round") != idx:
        other_names = [name for name in employee_names_original if name.lower() != correct_name_lower]
        dropdown_names = random.sample(other_names, 7) if len(other_names) >= 7 else other_names
        dropdown_names.append(correct_name_original)
        random.shuffle(dropdown_names)
        st.session_state.dropdown_names = dropdown_names
        st.session_state.dropdown_round = idx

    guess = st.selectbox("Who is this image about?", st.session_state.dropdown_names, key="guess_selectbox")

    user_key = st.session_state.user_name
    user_has_guessed = db.collection("game_state").document("current").collection("guesses").document(user_key).get().exists

    leaderboard = get_leaderboard()

    if not user_has_guessed:
        if st.button("Submit Guess"):
            correct = guess.strip().lower() == correct_name_lower.strip()
            db.collection("game_state").document("current").collection("guesses").document(user_key).set({
                "guess": guess,
                "correct": correct
            })
            if correct:
                # Update leaderboard
                current_score = leaderboard.get(user_key, 0) + 1
                set_leaderboard_entry(user_key, current_score)
                st.success("Correct!")
            else:
                st.error("Wrong! Try again next round.")
            st.rerun()
    else:
        st.info("You have already guessed this round. Wait for the next image!")

    # Next image button (host only, updates for all)
    if st.session_state.host_mode and st.button("Next Image"):
        # Clear guesses for next round
        reset_guesses()
        set_game_state({
            "current_index": idx + 1,
            "current_meme": None,
            "game_started": True,
            "game_over": False
        })
        st.rerun()
