# Code Generated by Sidekick is for learning and experimentation purposes only.

import streamlit as st
import pandas as pd
import openai
import configparser
import firebase_admin
from firebase_admin import credentials, firestore

# --- SECRETS HANDLING ---
def get_openai_key():
    try:
        return st.secrets["OPENAI_API_KEY"]
    except Exception:
        config = configparser.ConfigParser(interpolation=None)
        config.read('secrets.ini')
        return config['openai']['OPENAI_API_KEY']

def get_firestore_client():
    try:
        creds_dict = st.secrets["firestore_service_account"]
    except Exception:
        config = configparser.ConfigParser(interpolation=None)
        config.read('secrets.ini')
        fs_creds = config['firestore_service_account']
        creds_dict = {
            "type": fs_creds["type"],
            "project_id": fs_creds["project_id"],
            "private_key_id": fs_creds["private_key_id"],
            "private_key": fs_creds["private_key"].replace('\\n', '\n'),
            "client_email": fs_creds["client_email"],
            "client_id": fs_creds["client_id"],
            "auth_uri": fs_creds["auth_uri"],
            "token_uri": fs_creds["token_uri"],
            "auth_provider_x509_cert_url": fs_creds["auth_provider_x509_cert_url"],
            "client_x509_cert_url": fs_creds["client_x509_cert_url"],
            "universe_domain": fs_creds.get("universe_domain", "googleapis.com")
        }
    # Initialize Firebase app if not already initialized
    if not firebase_admin._apps:
        cred = credentials.Certificate(creds_dict)
        firebase_admin.initialize_app(cred)
    return firestore.client()

# --- FIRESTORE SETUP ---
db = get_firestore_client()

# --- CONFIGURATION ---
OPENAI_API_KEY = get_openai_key()
client = openai.OpenAI(api_key=OPENAI_API_KEY)
HOST_SECRET = "123"
EXCEL_FILE = "employee_info.xlsx"

# --- SESSION STATE INITIALIZATION ---
if "game_started" not in st.session_state:
    st.session_state.game_started = False
if "host_mode" not in st.session_state:
    st.session_state.host_mode = False
if "user_name" not in st.session_state:
    st.session_state.user_name = None
if "has_registered" not in st.session_state:
    st.session_state.has_registered = False

st.title("FunFriday Meme Game")

# --- LOAD EMPLOYEE DATA ---
@st.cache_data
def load_employee_data():
    df = pd.read_excel(EXCEL_FILE)
    for col in ["Name", "FunFact", "Hobby"]:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")
    return df

try:
    df = load_employee_data()
except Exception as e:
    st.error(f"Error loading employee data: {e}")
    st.stop()

employee_names = df["Name"].tolist()

# --- FIRESTORE HELPERS ---
def get_game_state():
    doc = db.collection("game_state").document("current").get()
    return doc.to_dict() if doc.exists else None

def set_game_state(state):
    db.collection("game_state").document("current").set(state)

def get_leaderboard():
    docs = db.collection("leaderboard").stream()
    return {doc.id: doc.to_dict()["score"] for doc in docs}

def set_leaderboard(leaderboard):
    for name, score in leaderboard.items():
        db.collection("leaderboard").document(name).set({"Name": name, "score": score})

def reset_firestore_state():
    db.collection("game_state").document("current").set({
        "current_index": 0,
        "current_meme": None,
        "game_started": False
    })
    for name in employee_names:
        db.collection("leaderboard").document(name).set({"Name": name, "score": 0})

# --- HOST CONTROLS ---
with st.sidebar:
    st.header("Host Controls")
    if not st.session_state.host_mode:
        host_code = st.text_input("Enter host secret to unlock controls", type="password")
        if st.button("Unlock Host Controls"):
            if host_code == HOST_SECRET:
                st.session_state.host_mode = True
                st.success("Host controls unlocked!")
            else:
                st.error("Incorrect secret.")
    else:
        game_state = get_game_state()
        if not game_state or not game_state.get("game_started", False):
            if st.button("Start Game"):
                reset_firestore_state()
                set_game_state({
                    "current_index": 0,
                    "current_meme": None,
                    "game_started": True
                })
                set_leaderboard({name: 0 for name in employee_names})
        else:
            if st.button("Stop Game"):
                set_game_state({**game_state, "game_started": False})
        if st.button("Reset Game"):
            reset_firestore_state()
            st.session_state.host_mode = False

    # Leaderboard (Host only)
    if st.session_state.host_mode:
        st.subheader("Leaderboard (Top 5)")
        leaderboard = get_leaderboard()
        sorted_leaderboard = sorted(leaderboard.items(), key=lambda x: x[1], reverse=True)[:5]
        for i, (uname, score) in enumerate(sorted_leaderboard, 1):
            st.write(f"{i}. {uname}: {score}")

# --- USER REGISTRATION ---
if not st.session_state.has_registered:
    st.subheader("Enter Your Name")
    user_name = st.text_input("Your Name")
    if st.button("Register"):
        if user_name and user_name in employee_names:
            st.session_state.user_name = user_name
            st.session_state.has_registered = True
            st.success(f"Welcome, {user_name}! Wait for the host to start the game.")
        elif user_name:
            st.warning("Name not found in employee list.")
        else:
            st.warning("Please enter your name.")
    st.stop()
else:
    st.info(f"Welcome, {st.session_state.user_name}! Wait for the host to start the game." if not get_game_state() or not get_game_state().get("game_started", False) else "")

# --- GAME PHASE ---
game_state = get_game_state()
if game_state and game_state.get("game_started", False):
    idx = game_state["current_index"]
    if idx >= len(df):
        st.success("Game Over! All employees have had their meme.")
        st.balloons()
        set_game_state({**game_state, "game_started": False})
        st.stop()

    emp = df.iloc[idx]
    meme_prompt = f"Create a funny meme caption about this person: Fun Fact: {emp['FunFact']}, Hobby: {emp['Hobby']}"

    # Generate meme only once per round (store in Firestore)
    if not game_state.get("current_meme"):
        response = client.chat.completions.create(
            model="gpt-4",
            messages=[{"role": "user", "content": meme_prompt}]
        )
        meme_text = response.choices[0].message.content
        set_game_state({**game_state, "current_meme": meme_text})
        game_state = get_game_state()  # Refresh

    st.header(f"Meme for: ???")
    st.write(f"**Meme:** {game_state['current_meme']}")

    # Guessing section
    leaderboard = get_leaderboard()
    user_has_guessed = db.collection("game_state").document("current").collection("guesses").document(st.session_state.user_name).get().exists

    if not user_has_guessed:
        guess = st.selectbox("Who is this meme about?", employee_names)
        if st.button("Submit Guess"):
            if st.session_state.user_name:
                correct = guess == emp["Name"]
                db.collection("game_state").document("current").collection("guesses").document(st.session_state.user_name).set({
                    "guess": guess,
                    "correct": correct
                })
                if correct:
                    leaderboard[st.session_state.user_name] = leaderboard.get(st.session_state.user_name, 0) + 1
                    set_leaderboard(leaderboard)
                    st.success("Correct!")
                else:
                    st.error("Wrong! Try again next round.")
            else:
                st.warning("Please register your name first.")
    else:
        st.info("You have already guessed this round. Wait for the next meme!")

    # Next meme button (host only, updates meme and leaderboard for all)
    if st.session_state.host_mode and st.button("Next Meme"):
        # Clear guesses for next round
        guesses_ref = db.collection("game_state").document("current").collection("guesses")
        for doc in guesses_ref.stream():
            doc.reference.delete()
        set_game_state({
            "current_index": idx + 1,
            "current_meme": None,
            "game_started": True
        })

else:
    if st.session_state.has_registered:
        st.info("Waiting for host to start the game.")
